# Changes here will be overwritten by Copier
_commit: v1.4.6
_src_path: gh:lincc-frameworks/python-project-template
author_email: lincc-frameworks-team@lists.lsst.org
author_name: LINCC Frameworks
create_example_module: false
custom_install: true
include_benchmarks: false
include_docs: false
mypy_type_checking: none
package_name: lf_workflow_dash
preferred_linter: pylint
project_license: MIT
project_name: lf_workflow_dash
project_organization: lincc-frameworks
use_isort: true
