page_title: LF Workflow Dashboard

repos:
  - repo: asv-formatter
    owner: lincc-frameworks
    workflows:
      - smoke-test.yml
      - testing-and-coverage.yml
      - build-documentation.yml
  
  - repo: asv-formatter
    owner: lincc-frameworks
    workflows:
      - smoke-test.yml
      - testing-and-coverage.yml
  
  - repo: hipscat
    owner: astronomy-commons
    workflows:
      - smoke-test.yml
      - testing-and-coverage.yml
      - asv-nightly.yml
      - build-documentation.yml
  
  - repo: hipscat-import
    owner: astronomy-commons
    workflows:
      - smoke-test.yml
      - testing-and-coverage.yml
      - build-documentation.yml
  
  - repo: kbmod
    owner: dirac-institute
    workflows:
      - build_docs.yaml
      - canary_builds.yaml
      - pr_tests.yaml
  
  - repo: koffi
    owner: lincc-frameworks
    workflows:
      - smoke-test.yml
      - testing-and-coverage.yml
  
  - repo: lsdb
    owner: astronomy-commons
    workflows:
      - smoke-test.yml
      - testing-and-coverage.yml
      - asv-nightly.yml
      - build-documentation.yml
      
  - repo: metric-emitter
    owner: lincc-frameworks
    workflows:
      - smoke-test.yml
      - testing-and-coverage.yml
  
  - repo: python-project-template
    owner: lincc-frameworks
    workflows:
      - ci.yml
  
  - repo: rail
    owner: lsstdesc
    workflows:
      - smoke-test.yml
      - testing-and-coverage.yml
      - build_documentation.yml
  
  - repo: rail_base
    owner: lsstdesc
    workflows:
      - smoke-test.yml
      - testing-and-coverage.yml
  
  - repo: rail_pipelines
    owner: lsstdesc
    workflows:
      - main.yml
  
  - repo: tables_io
    owner: lsstdesc
    workflows:
      - smoke-test.yml
      - testing-and-coverage.yml
  
  - repo: tape
    owner: lincc-frameworks
    workflows:
      - smoke-test.yml
      - testing-and-coverage.yml
      - build-documentation.yml
  
  - repo: tape_benchmarking
    owner: lincc-frameworks
    workflows:
      - smoke-test.yml
      - testing-and-coverage.yml
      - build-documentation.yml
