# Run this to update the html dashboards. Will run automatically as well.

name: Update dashboard html
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  run_update:
    runs-on: ubuntu-latest
    steps:
      - name: Get Timestamp Action
        uses: nanzm/get-time-action@v2.0
        id: time
        with:
          # timeZone: UTC-4
          format: 'YYYY-MM-DD HH:mm'
      - name: Usage
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
            echo $TIME
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get update
          python -m pip install --upgrade pip
          pip install .
      - run: |
          python update_dashboard.py ${{ secrets.GITHUB_TOKEN }} tracked_workflows.yaml index.html
          python update_dashboard.py ${{ secrets.GITHUB_TOKEN }} rail_tracked_workflows.yaml rail.html
          python update_dashboard_group.py ${{ secrets.GITHUB_TOKEN }} tracked_workflows_group.yaml index_group.html
          python update_dashboard_group.py ${{ secrets.GITHUB_TOKEN }} rail_tracked_workflows_group.yaml rail_group.html
      - name: Commit and push changes
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
          git config --global user.name "OliviaLynn"
          git config --global user.email "olynn@andrew.cmu.edu"
          git add -A
          git commit -m "Auto updated $TIME"
          git push
